import Head from "next/head";
import Image from "next/image";
import dynamic from "next/dynamic";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>My Mexico Tours</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <div className="flex flex-wrap mt-16">
          <div className="w-1/2 md:w-1/3 lg:w-1/3">
            <a class="relative block bg-gray-900 group" href="#">
              <Image
                src="https://d1coydiqa46lxm.cloudfront.net/fp/mmt-next-fp-4.jpeg"
                alt=""
                width="700"
                height="500"
                className="block h-auto w-full absolute inset-0 object-cover group-hover:opacity-50"
              />
              <div class="relative p-2">
                <div class="mt-40">
                  <div class="transition-all transform translate-y-8 opacity-0 group-hover:opacity-100 group-hover:translate-y-0">
                    <div class="p-2">
                      <h2 class="text-center text-2xl text-white">Betsy</h2>
                    </div>
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div className="w-1/2 md:w-1/3 lg:w-1/3">
            <a class="relative block bg-gray-900 group" href="tours">
              <Image
                src="https://d1coydiqa46lxm.cloudfront.net/fp/mmt-next-fp-10.jpeg"
                alt=""
                width="700"
                height="500"
                className="block h-auto w-full absolute inset-0 object-cover group-hover:opacity-50"
              />
              <div class="relative p-2">
                <div class="mt-40">
                  <div class="transition-all transform translate-y-8 opacity-0 group-hover:opacity-100 group-hover:translate-y-0">
                    <div class="p-2">
                      <h2 class="text-center text-2xl text-white">My Tours</h2>
                    </div>
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div className="w-1/2 md:w-1/3 lg:w-1/3">
            <a class="relative block bg-gray-900 group" href="tours">
              <Image
                src="https://d1coydiqa46lxm.cloudfront.net/fp/mmt-next-fp-14.jpeg"
                alt=""
                width="700"
                height="500"
                className="block h-auto w-full absolute inset-0 object-cover group-hover:opacity-50"
              />
              <div class="relative p-2">
                <div class="mt-40">
                  <div class="transition-all transform translate-y-8 opacity-0 group-hover:opacity-100 group-hover:translate-y-0">
                    <div class="p-2">
                      <h2 class="text-center text-2xl text-white">
                        Your Tours
                      </h2>
                    </div>
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div className="w-1/2 md:w-1/3 lg:w-1/3">
            <a class="relative block bg-gray-900 group" href="tours">
              <Image
                src="https://d1coydiqa46lxm.cloudfront.net/fp/mmt-next-fp-17.jpeg"
                alt=""
                width="700"
                height="500"
                className="block h-auto w-full absolute inset-0 object-cover group-hover:opacity-50"
              />
              <div class="relative p-2">
                <div class="mt-40">
                  <div class="transition-all transform translate-y-8 opacity-0 group-hover:opacity-100 group-hover:translate-y-0">
                    <div class="p-2">
                      <h2 class="text-center text-2xl text-white">
                        Mexicocina
                      </h2>
                    </div>
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div className="w-1/2 md:w-1/3 lg:w-1/3">
            <a class="relative block bg-gray-900 group" href="tours">
              <Image
                src="https://d1coydiqa46lxm.cloudfront.net/fp/mmt-next-fp-24.jpeg"
                alt=""
                width="700"
                height="500"
                className="block h-auto w-full absolute inset-0 object-cover group-hover:opacity-50"
              />
              <div class="relative p-2">
                <div class="mt-40">
                  <div class="transition-all transform translate-y-8 opacity-0 group-hover:opacity-100 group-hover:translate-y-0">
                    <div class="p-2">
                      <h2 class="text-center text-2xl text-white">
                        What&lsquo;s New
                      </h2>
                    </div>
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div className="w-1/2 md:w-1/3 lg:w-1/3">
            <a class="relative block bg-gray-900 group" href="tours">
              <Image
                src="https://d1coydiqa46lxm.cloudfront.net/fp/mmt-next-fp-30.jpeg"
                alt=""
                width="700"
                height="500"
                className="block h-auto w-full absolute inset-0 object-cover group-hover:opacity-50"
              />
              <div class="relative p-2">
                <div class="mt-40">
                  <div class="transition-all transform translate-y-8 opacity-0 group-hover:opacity-100 group-hover:translate-y-0">
                    <div class="p-2">
                      <h2 class="text-center text-2xl text-white">Food</h2>
                    </div>
                  </div>
                </div>
              </div>
            </a>
          </div>
        </div>
      </main>
    </div>
  );
}
