import Head from "next/head";
import Image from "next/image";
import dynamic from "next/dynamic";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import data from "../data/fpitems.json";

export default function Home() {
  return (
    <div>
      <Head>
        <title>My Mexico Tours</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="grid mt-16">
        <div className="grid overflow-hidden sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3 2xl:grid-cols-3 grid-rows-2 gap-0 grid-flow-row w-auto 2xl:h-auto 2xl:square">
          {data.map((item) => (
            <div className="box" key={item.id}>
              <div className="gridimg square lg:aspect-[4/3] sm:aspect-[4/3]">
                <a
                  className="relative block bg-gray-900 group"
                  href={item.websiteUrl}
                >
                  <Image
                    src={item.imgUrl}
                    alt=""
                    width="700"
                    height="500"
                    className="block h-auto w-full absolute square inset-0 object-cover group-hover:opacity-50"
                    loading="eager"
                    priority={true}
                  />
                  <div className="relative p-2">
                    <div className="mt-40">
                      <div className="transition-all transform translate-y-8 opacity-0 group-hover:opacity-100 group-hover:translate-y-0">
                        <div className="p-2">
                          <h2 className="text-center text-2xl text-white">
                            {item.name}
                          </h2>
                        </div>
                      </div>
                    </div>
                  </div>
                </a>
              </div>
            </div>
          ))}
          ;
        </div>
        <Footer />
      </main>
    </div>
  );
}
