import Head from 'next/head'
import Image from 'next/image'
import dynamic from 'next/dynamic'
import Navbar from "../components/Navbar";

export default function Home() {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
      <div className="flex flex-wrap mt-16">
        <div className="w-1/2 md:w-1/3 lg:w-1/3">
          <Image
          src="https://d1coydiqa46lxm.cloudfront.net/fp/mmt-next-fp-4.jpeg"
          alt=""
          width="700"
          height="500"
          className="block h-auto w-full"
          />
          </div>
          <div className="w-1/2 md:w-1/3 lg:w-1/3">
          <Image
          src="https://d1coydiqa46lxm.cloudfront.net/fp/mmt-next-fp-10.jpeg"
          alt=""
          width="700"
          height="500"
          className="block h-auto w-full"
          />
          </div>
          <div className="w-1/2 md:w-1/3 lg:w-1/3">
          <Image
          src="https://d1coydiqa46lxm.cloudfront.net/fp/mmt-next-fp-14.jpeg"
          alt=""
          width="700"
          height="500"
          className="block h-auto w-full"
          />
          </div>
          <div className="w-1/2 md:w-1/3 lg:w-1/3">
          <Image
          src="https://d1coydiqa46lxm.cloudfront.net/fp/mmt-next-fp-17.jpeg"
          alt=""
          width="700"
          height="500"
          className="block h-auto w-full"
          />
          </div>
          <div className="w-1/2 md:w-1/3 lg:w-1/3">
          <Image
          src="https://d1coydiqa46lxm.cloudfront.net/fp/mmt-next-fp-24.jpeg"
          alt=""
          width="700"
          height="500"
          className="block h-auto w-full"
          />
          </div>
          <div className="w-1/2 md:w-1/3 lg:w-1/3">
          <Image
          src="https://d1coydiqa46lxm.cloudfront.net/fp/mmt-next-fp-30.jpeg"
          alt=""
          width="700"
          height="500"
          className="block h-auto w-full"
          />
          </div>
      </div>
      </main>
    </div>
  )
}
